const { Router } = require('express')
const uploadConfig = require("../config/upload")
const multer = require("multer")

const DishesController = require("../controllers/DishesController")
const SessionController = require("../controllers/SessionController")
const UsersController = require('../controllers/UsersController')
const UserRepository = require('../repositories/UserRepository')
const UserCreateService = require('../services/UserCreateService')
const ensureAuthenticated = require('../middlewares/ensureAuthenticated')
const ensureIsAdmin = require('../middlewares/ensureIsAdmin')
const routes = Router()
const upload = multer(uploadConfig.MULTER)
const dishesController = new DishesController()
const sessionController = new SessionController()
const userRepository = new UserRepository()
const userCreateService = new UserCreateService(userRepository)
const usersController = new UsersController(userCreateService)

routes.post('/session', sessionController.create)
routes.post('/register', (req, res) => usersController.create(req, res))
routes.get('/dishes', ensureAuthenticated, dishesController.show)
routes.get('/dishes/:id', ensureAuthenticated, dishesController.get)
routes.post('/dishes', ensureAuthenticated, ensureIsAdmin, upload.single("photo"), dishesController.create)
routes.delete('/dishes/:id', ensureAuthenticated, ensureIsAdmin, dishesController.delete)

module.exports = routes